accelerate launch --main_process_port 29501 scripts/dav.py \
--config config/dav.py \
--config.run_name compressibility \
--config.reward_fn jpeg_compressibility \
--config.prompt_fn simple_animals \
--config.train.learning_rate 1e-3 \
--config.sample.num_steps 50 \
--config.num_epochs 10 \
--config.eval.eval_freq 1 \
--config.save_freq 2 \
--config.seed 0 \
--config.sample.num_prompts_per_batch 16 \
--config.sample.num_batches_per_epoch 16 \
--noconfig.search.value_gradient \
--config.search.search_kl 0.005 \
--config.search.duplicate 16 \
--config.search.gamma 0.90 \
--config.search.importance_sampling \
--config.search.hill_climbing \
--config.train.improve_steps 1 \
--config.train.train_kl 0.01 \
